import type { SocialUser } from './types';

const blueYoyoAvatar = require('../../../assets/mock/social/yoyo-blue.jpg') as number;
const bearingAvatar = require('../../../assets/mock/social/yoyo-bearing.jpg') as number;

export const mockUsers: SocialUser[] = [
  {
    id: 'user-lin',
    handle: 'linloops',
    displayName: '阿林',
    avatarUri: blueYoyoAvatar,
    bio: '下班后练 1A，也在补 5A 基础。',
    city: '上海',
    styleTags: ['1A', '5A'],
  },
  {
    id: 'user-chen',
    handle: 'chenstring',
    displayName: '陈弦',
    avatarUri: bearingAvatar,
    bio: '把复杂连招拆成能每天练十分钟的小节。',
    city: '广州',
    styleTags: ['1A', '3A'],
    roleLabel: '教练',
  },
  {
    id: 'user-xiaoyu',
    handle: 'xiaoyu5a',
    displayName: '小宇',
    avatarUri: blueYoyoAvatar,
    bio: '5A 选手，喜欢研究自由手节奏。',
    city: '成都',
    styleTags: ['1A', '5A'],
    roleLabel: '赛事选手',
  },
  {
    id: 'user-mori',
    handle: 'mori2a',
    displayName: '森森',
    avatarUri: bearingAvatar,
    bio: '双手循环练习记录，偶尔写现场观察。',
    city: '杭州',
    styleTags: ['2A'],
  },
  {
    id: 'user-zhou',
    handle: 'zhouoffstring',
    displayName: '周周',
    avatarUri: blueYoyoAvatar,
    bio: '4A 抛接和舞台编排。',
    city: '武汉',
    styleTags: ['4A'],
    roleLabel: '表演者',
  },
  {
    id: 'user-aiko',
    handle: 'aikotriple',
    displayName: '爱可',
    avatarUri: bearingAvatar,
    bio: '三球同步很慢，但每天都有一点进度。',
    city: '北京',
    styleTags: ['3A'],
  },
  {
    id: 'user-maya',
    handle: 'mayabinds',
    displayName: 'Maya',
    avatarUri: blueYoyoAvatar,
    bio: '新手友好聚会发起人。',
    city: '深圳',
    styleTags: ['1A'],
    roleLabel: '活动组织者',
  },
  {
    id: 'user-tao',
    handle: 'taoyoyo',
    displayName: '陶然',
    avatarUri: bearingAvatar,
    bio: '赛事摄影、老球收藏和一点 5A。',
    city: '南京',
    styleTags: ['1A', '5A'],
    roleLabel: '收藏者',
  },
  {
    id: 'user-qi',
    handle: 'qibearings',
    displayName: '齐工',
    avatarUri: blueYoyoAvatar,
    bio: '轴承、回收系统与日常维护。',
    city: '苏州',
    styleTags: ['1A', '4A'],
    roleLabel: '器材研究',
  },
  {
    id: 'user-wen',
    handle: 'wenpractice',
    displayName: '文一',
    avatarUri: bearingAvatar,
    bio: '从零开始学 2A，记录真实失误率。',
    city: '西安',
    styleTags: ['2A'],
  },
  {
    id: 'user-leo',
    handle: 'leocounterweight',
    displayName: 'Leo',
    avatarUri: blueYoyoAvatar,
    bio: '自由手、音乐剪辑和速度连招。',
    city: '重庆',
    styleTags: ['3A', '5A'],
  },
  {
    id: 'user-nora',
    handle: 'norathrows',
    displayName: 'Nora',
    avatarUri: bearingAvatar,
    bio: '周末练 4A，工作日看比赛录像。',
    city: '青岛',
    styleTags: ['1A', '4A'],
  },
];
